function [L, D, p, S, B] = ildl(A, fill, tol)
%ILDL   Incomplete LDL factorization of indefinite Hermitian matrices.
%Before factoring, the matrix is equilibriated (resulting in a matrix S)
%and then permuted by the Reverse Cuthill-McKee algorithm.
%
%   [L, D, p, S, B] = ILDL(A, fill_factor, tol) attempts to factor A into the form
%   B = P'SASP = LDL', where P is the permutation matrix generated by the
%   permutation vector p. During factorization, Bunch-Kaufman partial
%   pivoting is used to maintain stability.
%
%   Parameters:
%       A - an n x n indefinite Hermitian matrix.
%
%       fill_factor - a parameter to control memory usage. Each column of L will
%       have at most fill_factor*nnz(A)/n non-zero elements.
%
%       tol - a parameter to control accuracy. For the each column of L, 
%       elements less than norm(column(L), 1) will be dropped.
%
%   Outputs:
%       L - unit lower triangular factor of P'SASP.
%
%       D - block diagonal factor (with 1x1 and 2x2 blocks) of P'SASP.
%
%       p - permutation vector of permutations done to A.
%
%       S - diagonal scaling matrix used to equilibriate A in the max-norm.
%
%       B - the scaled and permutated matrix B = P'SASP after
%       factorization.
%
%   Further documentation can be found <a href="http://www.cs.ubc.ca/~inutard/html/">here</a>.