%tests the factorization generated by matrix-factor
clc; %warning off;
mat_names = [];
for i = 1:8
    mat_names = [mat_names; strcat('testmat', num2str(i))];
end
mat_names = cellstr(mat_names);
other_mats = { 'aug3dcqp'; 'bloweya'; 'bratu3d'; ...
            'tuma1'; 'tuma2'; '1138_bus'};
        
all_mats = mat_names;

lfil = 0;
tol = 0;
for i = 1:length(all_mats)
    mat_name = all_mats{i};
    fprintf('Now testing %s:\n', mat_name);
    base = '';
    file = strcat(base, mat_name, '.mtx');
    %base = 'C:\Users\Paul\Documents\My Dropbox\Online Resources\My
    %Homework\UBC 2011W\NSERC\matrix-factor-recode\';

    cmd = horzcat('ldl_driver ', num2str(lfil), ' ', num2str(tol), ... 
                 ' test_matrices/', file, ' -n -n');
    [~, ~] = system(cmd);

    A = mmread(file);
    B = mmread(strcat(base, 'outA.mtx'));
    S = mmread(strcat(base, 'outS.mtx'));

    p = mmread(strcat(base, 'outPerm.mtx'));
    p = diag(p)+1;
   
    fprintf('The relative residual is %d.\n', norm(S*B*S- A(p,p), 1)/norm(B, 1));

%     close all;
%     spy(A); figure; spy(B)
%     p = symrcm(A);
%     figure; spy(A(p,p))

    fprintf('\n');
end

%warning on;
