#-*-mode:makefile-*-

all: _cppsparse.pyd

cppsparse_wrap.cxx: cppsparse.i
	swig -c++ -python -includeall -ignoremissing $<

cppsparse_wrap.o : cppsparse_wrap.cxx
	C:/Python26/Python.exe mingwpatch.py cppsparse_wrap.cxx
	g++ -shared -std=c++0x -DMS_WIN64 -c -IC:/Python26/Include cppsparse_wrap.cxx

_cppsparse.pyd: cppsparse_wrap.o
	g++ -shared cppsparse_wrap.o libpython26.a -o _cppsparse.pyd

clean: 
	del cppsparse_wrap.o 
	del _cppsparse.pyd
	del cppsparse_wrap.cxx